### ISSUE TITLE
找不到post文件

### ISSUE THREAD

**Issue by chenjq666** [onewhitethreee/zhihu_tools#1]
post文件是什么鬼，找不到post文件？
错误信息：
```
Traceback (most recent call last):
  File "column_downloader.py", line 376, in <module>
    download_main()
  File "column_downloader.py", line 365, in download_main
    download_url(url,False)
  File "column_downloader.py", line 314, in download_url
    name = get_name(url)
  File "column_downloader.py", line 336, in get_name
    res = session.get(url)
  File "D:\python3.8.5\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\python3.8.5\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python3.8.5\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\python3.8.5\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\python3.8.5\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\python3.8.5\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\python3.8.5\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\python3.8.5\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\python3.8.5\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\python3.8.5\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\python3.8.5\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\python3.8.5\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
```

**Comment by onewhitethreee** [comment]
自行修改一下保存的文件位置

**Comment by chenjq666** [comment]
报错了，这是什么原因？
`Traceback (most recent call last):
  File "column_downloader.py", line 376, in <module>
    download_main()
  File "column_downloader.py", line 365, in download_main
    download_url(url,False)
  File "column_downloader.py", line 314, in download_url
    name = get_name(url)
  File "column_downloader.py", line 336, in get_name
    res = session.get(url)
  File "D:\python3.8.5\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\python3.8.5\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python3.8.5\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\python3.8.5\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\python3.8.5\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\python3.8.5\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\python3.8.5\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\python3.8.5\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\python3.8.5\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\python3.8.5\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\python3.8.5\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\python3.8.5\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname`
